project_id = "zzkwldfssxopclqsxtku"

[functions.health-check]
verify_jwt = false

[functions.server-metrics]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.discover-services]
verify_jwt = false
